'use client';

import { useState } from 'react';
import { SummaryResponse, MeetingStructure, EnhancedSummaryResponse } from '@/lib/types';
import { FileText, List, CheckCircle, ListTodo, Edit2, Check, Sparkles } from 'lucide-react';
import MeetingLayout from './MeetingLayout';

interface SummaryPanelProps {
  summary?: SummaryResponse;
  enhancedSummary?: EnhancedSummaryResponse;
}

// Legacy flat summary view (for backwards compatibility)
function LegacySummaryView({ summary }: { summary: SummaryResponse }) {
  const [isEditingTldr, setIsEditingTldr] = useState(false);
  const [editedTldr, setEditedTldr] = useState(summary.tldr);
  const [editedKeyPoints, setEditedKeyPoints] = useState(summary.key_points);
  const [editedDecisions, setEditedDecisions] = useState(summary.decisions);
  const [editedActionItems, setEditedActionItems] = useState(summary.action_items);

  const sections = [
    {
      id: 'tldr',
      title: 'TL;DR',
      icon: FileText,
      content: editedTldr,
      color: 'blue',
      isEditing: isEditingTldr,
      setIsEditing: setIsEditingTldr,
      editedContent: editedTldr,
      setEditedContent: setEditedTldr,
      isList: false,
    },
    {
      id: 'key_points',
      title: 'Key Discussion Points',
      icon: List,
      content: editedKeyPoints,
      color: 'green',
      isList: true,
    },
    {
      id: 'decisions',
      title: 'Decisions Made',
      icon: CheckCircle,
      content: editedDecisions,
      color: 'purple',
      isList: true,
    },
    {
      id: 'action_items',
      title: 'Action Items',
      icon: ListTodo,
      content: editedActionItems,
      color: 'orange',
      isList: true,
    },
  ];

  const getColorClasses = (color: string) => {
    const colors: { [key: string]: { bg: string; text: string; border: string } } = {
      blue: { bg: 'bg-blue-50', text: 'text-blue-600', border: 'border-blue-200' },
      green: { bg: 'bg-green-50', text: 'text-green-600', border: 'border-green-200' },
      purple: { bg: 'bg-purple-50', text: 'text-purple-600', border: 'border-purple-200' },
      orange: { bg: 'bg-orange-50', text: 'text-orange-600', border: 'border-orange-200' },
    };
    return colors[color] || colors.blue;
  };

  return (
    <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
      <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
        <h2 className="text-xl font-semibold text-gray-900">AI Summary</h2>
        <p className="text-sm text-gray-500 mt-1">Basic summary format</p>
      </div>

      <div className="p-6 space-y-6">
        {sections.map((section) => {
          const Icon = section.icon;
          const colors = getColorClasses(section.color);

          return (
            <div
              key={section.id}
              className={`rounded-lg border ${colors.border} ${colors.bg} p-5`}
            >
              <div className="flex items-center justify-between mb-3">
                <div className="flex items-center space-x-2">
                  <Icon className={`w-5 h-5 ${colors.text}`} />
                  <h3 className={`font-semibold ${colors.text}`}>{section.title}</h3>
                </div>
              </div>

              {section.isList ? (
                <ul className="space-y-2">
                  {(section.content as string[]).length > 0 ? (
                    (section.content as string[]).map((item, index) => (
                      <li key={index} className="flex items-start space-x-2">
                        <span className={`${colors.text} mt-1`}>•</span>
                        <span className="text-gray-700 flex-1">{item}</span>
                      </li>
                    ))
                  ) : (
                    <li className="text-gray-500 italic">None found</li>
                  )}
                </ul>
              ) : (
                <p className="text-gray-700 leading-relaxed">{section.content as string}</p>
              )}
            </div>
          );
        })}
      </div>

      <div className="bg-gray-50 px-6 py-4 border-t border-gray-200">
        <p className="text-sm text-gray-600 text-center">
          Generated by AI • Review and edit as needed
        </p>
      </div>
    </div>
  );
}

export default function SummaryPanel({ summary, enhancedSummary }: SummaryPanelProps) {
  // If we have enhanced summary, use the new hierarchical layout
  if (enhancedSummary) {
    return <MeetingLayout structure={enhancedSummary.structure} />;
  }

  // Fall back to legacy view if only simple summary is provided
  if (summary) {
    return <LegacySummaryView summary={summary} />;
  }

  // No summary available
  return (
    <div className="bg-white rounded-lg border border-gray-200 p-8 text-center">
      <Sparkles className="w-12 h-12 text-gray-300 mx-auto mb-4" />
      <h3 className="text-lg font-medium text-gray-700 mb-2">No Summary Available</h3>
      <p className="text-gray-500">Upload or record audio to generate a meeting summary.</p>
    </div>
  );
}
